/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package pi.telas;

import javax.swing.*;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;

/**
 *
 * @author muril
 */

public class HomePage extends javax.swing.JFrame {

    /**
     * Creates new form loadingPage
     */
    public HomePage() {
        setUndecorated(false);
        initComponents();

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated
    // <editor-fold defaultstate="collapsed" desc="Generated
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        background = new javax.swing.JPanel();
        logoImage = new javax.swing.JLabel();
        jogarButton = new javax.swing.JButton();
        gerenciarPerguntasButton = new javax.swing.JButton();
        sairButton = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(255, 255, 255));
        setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        setMinimumSize(new java.awt.Dimension(1080, 720));
        setPreferredSize(new java.awt.Dimension(1080, 720));
        setResizable(false);

        background.setBackground(new java.awt.Color(86, 1, 1));
        background.setPreferredSize(new java.awt.Dimension(1080, 720));
        java.awt.GridBagLayout jPanel1Layout1 = new java.awt.GridBagLayout();
        jPanel1Layout1.columnWidths = new int[] {0, 44, 0, 44, 0, 44, 0, 44, 0, 44, 0, 44, 0, 44, 0, 44, 0, 44, 0, 44, 0, 44, 0, 44, 0};
        jPanel1Layout1.rowHeights = new int[] {0, 35, 0, 35, 0, 35, 0, 35, 0, 35, 0, 35, 0, 35, 0, 35, 0, 35, 0, 35, 0, 35, 0};
        background.setLayout(jPanel1Layout1);

        logoImage.setIcon(new javax.swing.ImageIcon(getClass().getResource("/pi/newpackage/Logo-removebg.png"))); // NOI18N
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 12;
        gridBagConstraints.gridy = 2;
        background.add(logoImage, gridBagConstraints);

        jogarButton.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jogarButton.setText("Jogar");
        jogarButton.setPreferredSize(new java.awt.Dimension(300, 50));
        jogarButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jogarButtonActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 12;
        gridBagConstraints.gridy = 6;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        background.add(jogarButton, gridBagConstraints);

        gerenciarPerguntasButton.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        gerenciarPerguntasButton.setText("Gerenciar perguntas");
        gerenciarPerguntasButton.setPreferredSize(new java.awt.Dimension(300, 50));
        gerenciarPerguntasButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                gerenciarPerguntasButtonActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 12;
        gridBagConstraints.gridy = 8;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        background.add(gerenciarPerguntasButton, gridBagConstraints);

        sairButton.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        sairButton.setText("Sair");
        sairButton.setPreferredSize(new java.awt.Dimension(300, 50));
        sairButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                sairButtonActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 12;
        gridBagConstraints.gridy = 10;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        background.add(sairButton, gridBagConstraints);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(background, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(background, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jogarButtonActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_jogarButtonActionPerformed
            setVisible(false);
        // Cria um timer de 2000 milissegundos (2 segundos)
         // Inicia o timer
    }// GEN-LAST:event_jogarButtonActionPerformed

    private void rankingButtonActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_rankingButtonActionPerformed
        // TODO add your handling code here:
        // RankingPage ranking = new RankingPage();
        // ranking.setVisible(true);
        // Cria um timer de 2000 milissegundos (2 segundos)
        Timer timer = new Timer(10, new ActionListener() {
            @Override
            public void actionPerformed(ActionEvent e) {
                dispose(); // Fecha a janela atual (homePage) após 2 segundos
            }
        });

        timer.setRepeats(false); // Garante que o timer execute apenas uma vez
        timer.start(); // Inicia o timer
    }// GEN-LAST:event_rankingButtonActionPerformed

    private void gerenciarPerguntasButtonActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_gerenciarPerguntasButtonActionPerformed
        // TODO add your handling code here:
        LoginPage login = new LoginPage();
        login.setVisible(true);

    }// GEN-LAST:event_gerenciarPerguntasButtonActionPerformed

    private void sairButtonActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_sairButtonActionPerformed
        // TODO add your handling code here:
        dispose();
    }// GEN-LAST:event_sairButtonActionPerformed

    private void muteButtonActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_muteButtonActionPerformed
        // TODO add your handling code here:
    }// GEN-LAST:event_muteButtonActionPerformed

    private void muteButtonStateChanged(javax.swing.event.ChangeEvent evt) {// GEN-FIRST:event_muteButtonStateChanged
        // TODO add your handling code here:
    }// GEN-LAST:event_muteButtonStateChanged

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        // <editor-fold defaultstate="collapsed" desc=" Look and feel setting code
        // (optional) ">
        /*
         * If Nimbus (introduced in Java SE 6) is not available, stay with the default
         * look and feel.
         * For details see
         * http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(HomePage.class.getName()).log(java.util.logging.Level.SEVERE, null,
                    ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(HomePage.class.getName()).log(java.util.logging.Level.SEVERE, null,
                    ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(HomePage.class.getName()).log(java.util.logging.Level.SEVERE, null,
                    ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(HomePage.class.getName()).log(java.util.logging.Level.SEVERE, null,
                    ex);
        }
        // </editor-fold>
        // </editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new HomePage().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel background;
    private javax.swing.JButton gerenciarPerguntasButton;
    private javax.swing.JButton jogarButton;
    private javax.swing.JLabel logoImage;
    private javax.swing.JButton sairButton;
    // End of variables declaration//GEN-END:variables
}
